### ISSUE TITLE
[Feature-Parity] - SEO 

### ISSUE THREAD

**Issue by suddenlyGiovanni** [suddenlyGiovanni/suddenlygiovanni.dev#445]
# Problem statement:
- need a site-wide SEO solution
- need a specific SEO solution for separate context (e.g. blog post, resume, etc)

# Analisys:
different case scenario: `about-me` | `resume` | `blog` | `blog/${blog-posting}`

- base line requirements:
    each page should have a least the  
   - [x] custom title -> `<title>{title}</ title>`
   - [x] custom description -> `<meta name="description" content={description} />`
   - [x] custom url -> `<link rel="canonical" href={url} />`
   - [x] meta tags for `application-name` `author` `publisher` `creator` `keywords` `robots` `googlebot`
   - [x] base open graph protocol implementation
   - [x] base twitter custom graph protocol
   - [ ] base structure data support
- [x] it must support zero config base case
- [x] it must be overridable and extensible 

 
## TODOs:
- [ ] enable SEO support for all pages
- [x] enable an overridable SEO for specific needs.
